- hosts: aws-hongkong
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
    name:
    image:
    published_ports:
    env:
    restart_policy:
    volume:
    kernel_memory:
    memory:
    network_mode:
    state:
  roles:
    - config_container
