- name: update cache
  become: true
  becume_user: root
  apt:
    update_cache=yes
    force_apt_get=yes
  tags: update

- name: upgrade package
  become: true
  become_user: root
  apt:
    name: "*"
    state: latest
  tags: upgrade

- name: dist upgrade
  become: true
  become_user: root
  apt:
    upgrade=dist
    force_apt_get=yes
  tags: dist-upgrade
