- hosts: all-gcp-new
  tasks:
    - name: replace line in file
      become: true
      become_user: root
      replace:
        path: /etc/systemd/system/traceroute.service
        regexp: 'ExecStart=/usr/bin/python3 /home/user.supernet/traceroute/traceroute_tmp.py'
        replace: "ExecStart=/usr/bin/python3 /home/user.supernet/traceroute/traceroute.py"
