- name: create container
  docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    published_ports: "{{ published_port }}"
    env: "{{ environment }}"
    restart_policy: "{{ restart_policy }}"
    volume: "{{ volume }}"
    kernel_memory: "{{ kernel_memory }}"
    memory: "{{ memory }}"
    network_mode: "{{ network_mode }}"
  tags: create

- name: handler container
  docker_container:
    name: "{{ name }}"
    state: "{{ state }}"
  tags: handler
