- hosts: all-gcp
  tasks:
    - name: Running Container
      become: true
      docker_container:
        name: smokeping
        image: sysdamin/smokeping:1.0
        published_ports: 0.0.0.0:8080:80
        env: PUID=1000, PGID=1000
        restart_policy: always
        memory: 250M
