---
- hosts: all-gcp
  tasks:
#    - name: Update cache
#      become: true
#      become_user: root
#      apt:
#       update_cache=yes force_apt_get=yes
#    - name: Upgrade package
#      become: true
#      become_user: root
#      apt:
#       name: "*"
#       state: latest
    - name: Dist upgrade
      apt:
      become: true
      become_method: sudo
      become_user: user.supernet
       upgrade=dist force_apt_get=yes
