- hosts: all-aws
  tasks:
    - name: Update cache
      become: true
      become_user: root
      apt:
       update_cache=yes force_apt_get=yes
    - name: Upgrade package
      become: true
      become_user: root
      apt:
       name: "*"
       state: latest
    - name: Dist upgrade
      become: true
      become_user: root
      apt:
       upgrade=dist force_apt_get=yes
