- hosts: all-gcp-new
  tasks:
    - name: upload a main file
      become: true
      copy:
        src: /home/anonym/immobi/VA/Code/extract.sh
        dest: /home/user.supernet/hardening/extract.sh
        owner: root
        group: root

    - name: upload a extract.py file
      become: true
      copy:
        src: /home/anonym/immobi/VA/Code/extract_rrd.py
        dest: /home/user.supernet/hardening/extract_rrd.py
        owner: root
        group: root
