- name: checklist
  stat:
    apt:
      name:
        - python3-pip
        - python3
  register: python3_pip
  tags: install

- name: install python3-pip
  apt:
    name:
    - python3
    - python3-pip
    state: latest
  when: not python3_pip.stat.exists
  tags: install

- name: pip3-install
  pip:
    name: "{{ name }}"
    version: "{{ version | default(omit) }}"
    executable: pip3
  tags: install
